import { pdfPuzzleSpecs } from './pdfPuzzles.generated.js';
import { stationNamesByRoute } from './metroStations.js';

export const routes = [
  {
    id: 'line-1',
    number: '1',
    name: '1号线',
    subtitle: '基础杀法',
    color: '#e4002b',
    colorRgb: '228, 0, 43',
    dark: '#87162a',
    soft: '#ffe8e6',
    boardLight: '#ffe8d7',
    boardDark: '#ee8d8b',
    story: '第一条闯关主线，先把最直接的将杀图形练扎实。',
  },
  {
    id: 'line-2',
    number: '2',
    name: '2号线',
    subtitle: '后与长线',
    color: '#76b82a',
    colorRgb: '118, 184, 42',
    dark: '#315f24',
    soft: '#edf8dc',
    boardLight: '#f8edcf',
    boardDark: '#82b781',
    story: '沿着东西向主轴前进，练习后、车、象的长线控制。',
  },
  {
    id: 'line-3',
    number: '3',
    name: '3号线',
    subtitle: '波尔加题库',
    color: '#ffd100',
    colorRgb: '255, 209, 0',
    dark: '#85630b',
    soft: '#fff7cf',
    boardLight: '#fff3c4',
    boardDark: '#e5be3e',
    story: '从干净的残局图形开始，练习车、后、马的第一眼将杀。',
  },
  {
    id: 'line-4',
    number: '4',
    name: '4号线',
    subtitle: '黑方与综合',
    color: '#6f2c91',
    colorRgb: '111, 44, 145',
    dark: '#43205a',
    soft: '#f1e4f7',
    boardLight: '#f6e9fb',
    boardDark: '#a57abc',
    story: '绕城一圈，换到黑方视角，把前面的主题串起来。',
  },
  {
    id: 'line-5',
    number: '5',
    name: '5号线',
    subtitle: '残局基础',
    color: '#a05eb5',
    colorRgb: '160, 94, 181',
    dark: '#69357d',
    soft: '#f4e6f8',
    boardLight: '#f9ecfb',
    boardDark: '#bd91cd',
    story: '轻轨支线节奏更轻快，适合放入子力少、图形清楚的一步杀。',
  },
  {
    id: 'line-6',
    number: '6',
    name: '6号线',
    subtitle: '实战杀网',
    color: '#d5007f',
    colorRgb: '213, 0, 127',
    dark: '#7c164f',
    soft: '#ffe3f2',
    boardLight: '#ffe7f4',
    boardDark: '#e986bd',
    story: '沿着浦东一路向北，进入子力更多、但答案依然只有一步的杀网。',
  },
  {
    id: 'line-7',
    number: '7',
    name: '7号线',
    subtitle: '车后横线',
    color: '#f58220',
    colorRgb: '245, 130, 32',
    dark: '#8a4a13',
    soft: '#fff0dd',
    boardLight: '#fff1d8',
    boardDark: '#e9a75c',
    story: '从美兰湖一路向南，练习车和后的横线封锁。',
  },
  {
    id: 'line-8',
    number: '8',
    name: '8号线',
    subtitle: '边线压迫',
    color: '#00a3e0',
    colorRgb: '0, 163, 224',
    dark: '#0b6384',
    soft: '#e0f5ff',
    boardLight: '#e6f7ff',
    boardDark: '#71bada',
    story: '沿着城市南北中轴推进，把边王和底线压迫看清楚。',
  },
  {
    id: 'line-9',
    number: '9',
    name: '9号线',
    subtitle: '长线视野',
    color: '#71c5e8',
    colorRgb: '113, 197, 232',
    dark: '#3b6f84',
    soft: '#e9f8ff',
    boardLight: '#edfaff',
    boardDark: '#91cae1',
    story: '从松江到浦东，训练后、车、象的远程控制。',
  },
  {
    id: 'line-10',
    number: '10',
    name: '10号线',
    subtitle: '静着与封锁',
    color: '#c69ad6',
    colorRgb: '198, 154, 214',
    dark: '#714084',
    soft: '#f5e8fb',
    boardLight: '#f7e8fb',
    boardDark: '#b998ce',
    story: '这条线更像一串谜题，要看见安静的一步和被堵住的逃格。',
  },
  {
    id: 'line-11',
    number: '11',
    name: '11号线',
    subtitle: '长距转移',
    color: '#8c5a2b',
    colorRgb: '140, 90, 43',
    dark: '#5a3618',
    soft: '#f4eadf',
    boardLight: '#f8eddf',
    boardDark: '#b28b63',
    story: '长线路适合慢慢找关键格，练习跨半盘转移的一步杀。',
  },
  {
    id: 'line-12',
    number: '12',
    name: '12号线',
    subtitle: '换乘合围',
    color: '#007a53',
    colorRgb: '0, 122, 83',
    dark: '#084f39',
    soft: '#e0f3ea',
    boardLight: '#eaf8ee',
    boardDark: '#73aa93',
    story: '换乘密集的一线，适合练习多子配合后的最后一击。',
  },
  {
    id: 'line-13',
    number: '13',
    name: '13号线',
    subtitle: '安静一步',
    color: '#f6a6b2',
    colorRgb: '246, 166, 178',
    dark: '#965462',
    soft: '#fff0f3',
    boardLight: '#fff0f1',
    boardDark: '#eaa1ad',
    story: '看似安静的落点常常最有力，先数逃格再落子。',
  },
  {
    id: 'line-14',
    number: '14',
    name: '14号线',
    subtitle: '中心控制',
    color: '#c8a65a',
    colorRgb: '200, 166, 90',
    dark: '#755d2b',
    soft: '#f8efd8',
    boardLight: '#f8efd9',
    boardDark: '#c8aa6b',
    story: '穿过市中心的线路，用来训练中心格、斜线和横线的联动。',
  },
  {
    id: 'line-15',
    number: '15',
    name: '15号线',
    subtitle: '慢思考',
    color: '#b8a999',
    colorRgb: '184, 169, 153',
    dark: '#66594d',
    soft: '#f2eee8',
    boardLight: '#f8f1e7',
    boardDark: '#bba996',
    story: '这条线节奏舒展，适合把复杂局面拆成一个个逃格检查。',
  },
  {
    id: 'line-16',
    number: '16',
    name: '16号线',
    subtitle: '开阔局面',
    color: '#00a9a5',
    colorRgb: '0, 169, 165',
    dark: '#0d6462',
    soft: '#ddf7f5',
    boardLight: '#e7f8f5',
    boardDark: '#70bfbb',
    story: '开阔线路配开阔局面，练习远程子力一口气封王。',
  },
  {
    id: 'line-17',
    number: '17',
    name: '17号线',
    subtitle: '郊野长线',
    color: '#b07c2b',
    colorRgb: '176, 124, 43',
    dark: '#6d4b18',
    soft: '#f6eddd',
    boardLight: '#fbefd9',
    boardDark: '#c29a55',
    story: '向西延伸的闯关线，适合训练长线、边线和安静补位。',
  },
  {
    id: 'line-18',
    number: '18',
    name: '18号线',
    subtitle: '综合挑战',
    color: '#b6a268',
    colorRgb: '182, 162, 104',
    dark: '#6c5b2c',
    soft: '#f4efdf',
    boardLight: '#f7f0dc',
    boardDark: '#bda974',
    story: '把前面的主题混在一起，最后看谁能一眼找到将杀。',
  },
  {
    id: 'airport-link',
    number: 'AL',
    name: '机场联络线',
    subtitle: '待导入',
    color: '#1f5aa6',
    colorRgb: '31, 90, 166',
    dark: '#183d70',
    soft: '#e3efff',
    boardLight: '#eaf3ff',
    boardDark: '#7fa5d6',
    story: '线路框架已搭好，适合放入高速限时训练。',
  },
  {
    id: 'pujiang',
    number: 'PJ',
    name: '浦江线',
    subtitle: '待导入',
    color: '#8a8d8f',
    colorRgb: '138, 141, 143',
    dark: '#55585a',
    soft: '#eeeeee',
    boardLight: '#f3f3f0',
    boardDark: '#a5abad',
    story: '线路框架已搭好，适合放入短线复习题。',
  },
  {
    id: 'maglev',
    number: 'ML',
    name: '磁浮示范运营线',
    subtitle: '待导入',
    color: '#00a3ad',
    colorRgb: '0, 163, 173',
    dark: '#075a62',
    soft: '#dff7f8',
    boardLight: '#e6fbfb',
    boardDark: '#70bdc0',
    story: '线路框架已搭好，适合放入速度挑战和每日快题。',
  },
];

const routeById = new Map(routes.map((route) => [route.id, route]));

function routeFor(routeId) {
  return routeById.get(routeId) ?? routes[0];
}

function starBand(stars) {
  if (stars <= 1) return '入门';
  if (stars <= 2) return '基础';
  if (stars <= 3) return '进阶';
  if (stars <= 4) return '挑战';
  return '大师';
}

function stationFor(routeId, index = 0, puzzle = {}) {
  const route = routeFor(routeId);
  const stationNames = stationNamesByRoute[routeId] ?? [];
  const stationName = stationNames[index] ?? `${route.name}第 ${index + 1} 站`;
  const theme = puzzle.category ?? puzzle.motif ?? '一步杀';

  return {
    name: stationName,
    intro: `${stationName} 是 ${route.name} 按真实线路顺序排列的第 ${index + 1} 站。`,
    story: `这一站练习${theme}：先数清王的逃格，再找能立刻封住全局的那一步。`,
    nearby: `${stationName}周边探索 · 可继续补充照片、城市故事和亲子打卡线索`,
    photoGradient: `linear-gradient(135deg, ${route.color}, ${route.dark} 52%, #f4c84f)`,
  };
}

function buildTags(puzzle) {
  const tags = new Set(puzzle.tags ?? []);
  tags.add(puzzle.fen.includes(' w ') ? '白先' : '黑先');
  tags.add(puzzle.category ?? puzzle.motif ?? '一步杀');
  tags.add(starBand(puzzle.stars));

  if (puzzle.solutions?.length > 1) {
    tags.add('多答案');
  } else {
    tags.add('单答案');
  }

  return [...tags];
}

function enrichPuzzle(puzzle) {
  const category = puzzle.category ?? puzzle.motif ?? '一步杀';
  const routeIndex = puzzle.routeIndex ?? 0;

  return {
    ...puzzle,
    category,
    station: puzzle.station ?? stationFor(puzzle.routeId, routeIndex, { ...puzzle, category }),
    tags: buildTags({ ...puzzle, category }),
  };
}

const pdfPuzzles = pdfPuzzleSpecs.map((spec) =>
  enrichPuzzle({
    ...spec,
    station: stationFor(spec.routeId, spec.routeIndex, spec),
  }),
);

const polgarMetroStations = [
  {
    name: '上海南站',
    intro: '铁路和地铁交汇的南部门户，适合作为新题库的发车点。',
    story: '第一站先看最直的车线：像列车进站一样，一条线到底。',
    nearby: '上海南站、植物园、石龙路片区',
    photoGradient: 'linear-gradient(135deg, #ffd100, #e4002b 48%, #43a047)',
  },
  {
    name: '石龙路',
    intro: '靠近铁路与社区生活区，节奏比大站更安静。',
    story: '安静的位置常常藏着直接答案，先找王旁边被堵住的格子。',
    nearby: '石龙路、徐汇滨江南段、社区公园',
    photoGradient: 'linear-gradient(135deg, #ffd100, #81c784 52%, #78909c)',
  },
  {
    name: '龙漕路',
    intro: '3号线和12号线换乘站，像棋盘上的交叉火力点。',
    story: '车和兵把逃路框住，最后一步只需要把闸门合上。',
    nearby: '龙漕路、漕河泾、龙华片区',
    photoGradient: 'linear-gradient(135deg, #ffd100, #007a53 52%, #f58220)',
  },
  {
    name: '漕溪路',
    intro: '老城区、体育场和商业空间相邻，路线密集。',
    story: '双车题要看清两条线的分工：一条给将军，一条堵退路。',
    nearby: '上海体育场、漕溪路、徐家汇商圈',
    photoGradient: 'linear-gradient(135deg, #ffd100, #f15a24 52%, #1976d2)',
  },
  {
    name: '宜山路',
    intro: '多线换乘站，转角和通道很多，很适合做观察训练。',
    story: '边王题看起来空旷，其实王的每条路都被身边子力卡住。',
    nearby: '宜山路、光启城、徐汇商务区',
    photoGradient: 'linear-gradient(135deg, #ffd100, #6f2c91 52%, #8bc34a)',
  },
  {
    name: '虹桥路',
    intro: '3、4、10号线交汇，换乘感很强。',
    story: '马的跳跃控制很像换乘：不走直线，却刚好覆盖关键点。',
    nearby: '虹桥路、宋庆龄陵园、古北片区',
    photoGradient: 'linear-gradient(135deg, #ffd100, #c69ad6 52%, #4db6ac)',
  },
  {
    name: '延安西路',
    intro: '高架、老街区和城市绿意并行，是很有层次的一站。',
    story: '车象接力要看远线：先看被挡住的王，再看能切入的边线。',
    nearby: '延安西路、天山公园、长宁路沿线',
    photoGradient: 'linear-gradient(135deg, #ffd100, #455a64 52%, #ffb74d)',
  },
  {
    name: '中山公园',
    intro: '大型换乘站，商圈、公园和多条线路聚在一起。',
    story: '吃子也可以是将杀，关键是吃完后对方没有任何喘息格。',
    nearby: '中山公园、龙之梦、苏州河步道',
    photoGradient: 'linear-gradient(135deg, #ffd100, #00a3e0 52%, #7cb342)',
  },
  {
    name: '金沙江路',
    intro: '换乘和商业都很方便，适合做快速复习站。',
    story: '角落里的王最怕一条干净的车线，找到返航路线就好。',
    nearby: '金沙江路、环球港、华师大周边',
    photoGradient: 'linear-gradient(135deg, #ffd100, #71c5e8 52%, #f06292)',
  },
  {
    name: '曹杨路',
    intro: '多线换乘的老牌枢纽，线路关系很像复杂局面。',
    story: '象和车一起封王，先看被控制的逃格，再找最后一条直线。',
    nearby: '曹杨路、普陀区商业街区、武宁路',
    photoGradient: 'linear-gradient(135deg, #ffd100, #8c5a2b 52%, #64b5f6)',
  },
  {
    name: '莘庄',
    intro: '5号线起点，也是南上海通勤的重要节点。',
    story: '进入5号线后，题目从简洁残局继续加一点子力配合。',
    nearby: '莘庄、仲盛世界商城、莘庄公园',
    photoGradient: 'linear-gradient(135deg, #a05eb5, #e4002b 52%, #ffe082)',
  },
  {
    name: '春申路',
    intro: '社区气息浓，适合做轻量但扎实的练习站。',
    story: '王、马、车的位置很近，答案通常藏在贴身封锁里。',
    nearby: '春申路、闵行生活区、春申湖周边',
    photoGradient: 'linear-gradient(135deg, #a05eb5, #8bc34a 52%, #80cbc4)',
  },
  {
    name: '银都路',
    intro: '南部居住区的一站，节奏稳定。',
    story: '后远远站在角落，也能把王锁住；先看长线，再看逃格。',
    nearby: '银都路、莲花南路、社区商业',
    photoGradient: 'linear-gradient(135deg, #a05eb5, #c0ca33 52%, #607d8b)',
  },
  {
    name: '颛桥',
    intro: '闵行南部的重要社区站，周边生活感很强。',
    story: '后靠近王时，要小心自己的王也参与封锁。',
    nearby: '颛桥、闵行公园、老街片区',
    photoGradient: 'linear-gradient(135deg, #a05eb5, #ff7043 52%, #9ccc65)',
  },
  {
    name: '北桥',
    intro: '5号线一路向南，城市边界逐渐舒展开。',
    story: '这类题答案不一定是吃子，安静落点也能立即将死。',
    nearby: '北桥、沪闵路、剑川路方向',
    photoGradient: 'linear-gradient(135deg, #a05eb5, #26a69a 52%, #ffd54f)',
  },
  {
    name: '剑川路',
    intro: '靠近高校和产业园区，适合放一点更有计算感的题。',
    story: '后吃掉关键守兵后，王翼的全部出口同时关闭。',
    nearby: '剑川路、上海交通大学闵行校区、紫竹园区',
    photoGradient: 'linear-gradient(135deg, #a05eb5, #3f51b5 52%, #aed581)',
  },
  {
    name: '东川路',
    intro: '高校气质很浓的一站，适合慢看复杂关系。',
    story: '边线题的第一原则是：别急着走，先数每一个逃格。',
    nearby: '东川路、交大闵行校区、紫竹高新区',
    photoGradient: 'linear-gradient(135deg, #a05eb5, #00a9a5 52%, #ffcc80)',
  },
  {
    name: '金平路',
    intro: '5号线支线上的生活站，短小题很适合反复刷。',
    story: '后到中心并不只是将军，它还顺手关掉了王的所有出口。',
    nearby: '金平路、闵行社区、江川路片区',
    photoGradient: 'linear-gradient(135deg, #a05eb5, #f06292 52%, #4dd0e1)',
  },
  {
    name: '港城路',
    intro: '6号线北端站，靠近滨江和港区，空间更开阔。',
    story: '复杂局面里仍然只有一步，先找最像“闸门”的那一格。',
    nearby: '港城路、外高桥、浦东滨江北段',
    photoGradient: 'linear-gradient(135deg, #d5007f, #00a3e0 52%, #b2dfdb)',
  },
  {
    name: '外高桥保税区北',
    intro: '靠近外高桥片区，城市功能更偏产业和港区。',
    story: '后到三路像换乘到隐藏通道，一步就把逃路线封干净。',
    nearby: '外高桥保税区、港区道路、滨江空间',
    photoGradient: 'linear-gradient(135deg, #d5007f, #455a64 52%, #90caf9)',
  },
  {
    name: '航津路',
    intro: '6号线北段的重要社区站，适合放实战形态题。',
    story: '底线穿针需要看出后背后的长线，而不是只盯着王。',
    nearby: '航津路、外高桥生活区、张杨北路沿线',
    photoGradient: 'linear-gradient(135deg, #d5007f, #ffd100 52%, #4db6ac)',
  },
  {
    name: '外高桥保税区南',
    intro: '产业区与生活区相接，棋盘上的子力关系也更密。',
    story: '后落到五路时，横线、斜线和王旁边的兵一起形成网。',
    nearby: '外高桥保税区南、港城商业、浦东北路',
    photoGradient: 'linear-gradient(135deg, #d5007f, #007a53 52%, #ffb74d)',
  },
  {
    name: '洲海路',
    intro: '靠近浦东北侧社区，视野开阔。',
    story: '王翼的拥挤局面要先找王的气口，然后用后精准补上。',
    nearby: '洲海路、森兰商圈、外高桥片区',
    photoGradient: 'linear-gradient(135deg, #d5007f, #76b82a 52%, #64b5f6)',
  },
  {
    name: '五洲大道',
    intro: '交通干道和商业区相连，节奏很适合挑战题。',
    story: '吃掉f线守兵之后，将军和封锁同时发生。',
    nearby: '五洲大道、森兰绿地、浦东足球场周边',
    photoGradient: 'linear-gradient(135deg, #d5007f, #8c5a2b 52%, #a5d6a7)',
  },
  {
    name: '东靖路',
    intro: '生活区氛围明显，适合作为复杂题后的缓冲站。',
    story: '后到f3像点亮王翼信号灯，所有出口一瞬间变红。',
    nearby: '东靖路、金桥北片区、张杨北路',
    photoGradient: 'linear-gradient(135deg, #d5007f, #1f5aa6 52%, #ffd166)',
  },
  {
    name: '巨峰路',
    intro: '6号线与12号线换乘站，是浦东北部重要节点。',
    story: '最后一站是安静的后步，像在换乘大厅里找到唯一出口。',
    nearby: '巨峰路、金桥、12号线换乘',
    photoGradient: 'linear-gradient(135deg, #d5007f, #007a53 52%, #f6a6b2)',
  },
];

const polgarPreviewPuzzles = [
  ['polgar-preview-001', 'line-3', '车线升空', '6k1/5ppp/8/8/8/6P1/5PK1/R7 w - - 0 1', 'Ra8#', '车升底线', 620, 1],
  ['polgar-preview-003', 'line-3', '二横线封王', '6k1/5p1p/7P/8/8/6P1/2R4K/8 w - - 0 1', 'Rc8#', '车横线封锁', 640, 1],
  ['polgar-preview-004', 'line-3', '双车夹角', '4k3/R7/8/8/8/3K4/8/7R w - - 0 1', 'Rh8#', '双车底线', 650, 1],
  ['polgar-preview-005', 'line-3', '边王关门', 'k7/1pK5/8/8/8/7R/8/8 w - - 0 1', 'Ra3#', '车封边王', 660, 1],
  ['polgar-preview-006', 'line-3', '车马堵站', '8/kppN4/8/8/8/1P6/1KP5/2R5 w - - 0 1', 'Ra1#', '车马封锁', 680, 1],
  ['polgar-preview-007', 'line-3', '车象接力', '5rk1/5p2/5Bp1/8/8/8/5PK1/7R w - - 0 1', 'Rh8#', '车象配合', 700, 2],
  ['polgar-preview-008', 'line-3', '骑士吃门', 'k1b5/p2R4/1pN5/8/8/1K6/8/8 w - - 0 1', 'Rxa7#', '车马角落网', 710, 2],
  ['polgar-preview-009', 'line-3', '角落返航', 'R7/8/8/8/8/5K2/7p/6k1 w - - 0 1', 'Ra1#', '车返底线', 720, 2],
  ['polgar-preview-010', 'line-3', '象车围栏', '2r5/2p5/kpB5/8/2R5/1K6/8/8 w - - 0 1', 'Ra4#', '车象围困', 730, 2],
  ['polgar-preview-011', 'line-3', '马车压顶', '2R5/5pkp/5Np1/6P1/8/8/6K1/8 w - - 0 1', 'Rg8#', '车马压顶', 740, 2],
  ['polgar-preview-012', 'line-5', '王马车网', '4k3/7R/3KN3/8/8/8/8/8 w - - 0 1', 'Re7#', '近王封锁', 760, 2],
  ['polgar-preview-013', 'line-5', '后翼定格', '5k2/p7/5K2/8/8/8/Q7/8 w - - 0 1', 'Qf7#', '后近身封王', 780, 2],
  ['polgar-preview-014', 'line-5', '王边贴身', '5qk1/Q7/6K1/8/8/8/8/8 w - - 0 1', 'Qh7#', '后贴王杀', 800, 2],
  ['polgar-preview-015', 'line-5', '后翼回旋', 'Q7/8/5pkp/8/4rqPK/8/8/8 w - - 0 1', 'Qg8#', '后长线转移', 840, 3],
  ['polgar-preview-016', 'line-5', '后吃守兵', '4qrk1/5ppp/8/8/8/7P/1Q4PK/B7 w - - 0 1', 'Qxg7#', '后象协同', 860, 3],
  ['polgar-preview-017', 'line-5', '边线贴靠', 'kr6/7Q/1P6/8/2K5/8/8/8 w - - 0 1', 'Qa7#', '后兵封边', 820, 2],
  ['polgar-preview-019', 'line-5', '后到中心', '7Q/8/8/8/4q3/3k4/1K2p3/8 w - - 0 1', 'Qc3#', '后控中心', 880, 3],
  ['polgar-preview-020', 'line-5', '斜线补位', '1Q6/8/6p1/7p/6kP/6P1/5K2/q7 w - - 0 1', 'Qc8#', '后远程补位', 900, 3],
  ['polgar-preview-021', 'line-6', '后落三路', '2r1R3/pbq2k1p/1p4pP/3pp3/B7/P1Q5/1P3PP1/6K1 w - - 0 1', 'Qf3#', '后车交叉', 940, 4],
  ['polgar-preview-022', 'line-6', '底线穿针', '2n2k2/p4pp1/Pp5r/1B4Q1/1q1p4/6Pp/1P3P1P/6K1 w - - 0 1', 'Qd8#', '后穿底线', 930, 4],
  ['polgar-preview-023', 'line-6', '后到五路', '7r/1p1R3p/p3pkp1/Q7/2r1q2P/2P5/P4PP1/6K1 w - - 0 1', 'Qg5#', '后车合围', 960, 4],
  ['polgar-preview-026', 'line-6', '后到四路', 'q4rb1/3Q3r/6k1/8/Ppp5/1n2B1P1/1P5P/4RRK1 w - - 0 1', 'Qg4#', '后车象合围', 980, 4],
  ['polgar-preview-027', 'line-6', '吃兵终点', 'r1bqkbnr/1ppp1ppp/p1n5/4p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w - - 0 1', 'Qxf7#', '开局速杀', 900, 3],
  ['polgar-preview-028', 'line-6', '后吃堡垒', '2rqk2N/1p3r2/4b2p/p5pQ/P2B4/8/1P3PPP/4R1K1 w - - 0 1', 'Qxf7#', '后吃守点', 990, 4],
  ['polgar-preview-029', 'line-6', '王翼亮灯', 'r2bq1nr/pppnp1bp/3p1kp1/6N1/3PP3/8/PPP2PPP/RNBQK2R w - - 0 1', 'Qf3#', '后马开局杀', 1040, 4],
  ['polgar-preview-030', 'line-6', '后翼安静', 'r1bqr3/pppnbk1p/2p2ppB/8/3P4/5Q2/PPP1NPPP/R3K2R w - - 0 1', 'Qb3#', '后象安静杀', 1080, 5],
].map(([id, routeId, title, fen, solution, motif, rating, stars], index) => ({
  id,
  routeId,
  title,
  station: polgarMetroStations[index],
  fen,
  solution,
  motif,
  rating,
  stars,
  source: '拓展题库 - 波尔加一步杀',
}));

const builtInPuzzles = [
  ...polgarPreviewPuzzles,
  {
    id: 'wechat-entertainment-1',
    routeId: 'line-1',
    title: '星光后翼',
    station: {
      name: '人民广场',
      intro: '上海市中心的超级换乘站，地面上连着博物馆、剧院和南京路步行街。',
      story: '这里适合做第一站：人流汇聚像棋盘中心，第一步要学会看清所有线路。',
      nearby: '上海博物馆、人民公园、南京路步行街',
      photoGradient: 'linear-gradient(135deg, #ec5b4f, #ffc857 52%, #4db6ac)',
    },
    fen: '8/7K/Q7/4q3/8/7p/7p/7k w - - 0 1',
    solution: 'Qf1#',
    motif: '后斜线将杀',
    rating: 780,
    stars: 2,
    source: '拓展题库 - 娱乐一步杀',
  },
  {
    id: 'wechat-entertainment-2',
    routeId: 'line-1',
    title: '王翼锁门',
    station: {
      name: '徐家汇',
      intro: '商圈、教堂、书店和校园气质混在一起，是很有层次的城市节点。',
      story: '这题像徐家汇的路口：看似出口很多，真正能封住王路的只有一个点。',
      nearby: '徐家汇书院、徐家汇天主堂、港汇恒隆广场',
      photoGradient: 'linear-gradient(135deg, #b71c3a, #f48fb1 50%, #ffe082)',
    },
    fen: '2Q5/8/8/1K1k4/8/p7/8/B5q1 w - - 0 1',
    solution: 'Qc6#',
    motif: '后近身封锁',
    rating: 820,
    stars: 2,
    source: '拓展题库 - 娱乐一步杀',
  },
  {
    id: 'wechat-entertainment-3',
    routeId: 'line-1',
    title: '底线闪电',
    station: {
      name: '陕西南路',
      intro: '老洋房、梧桐树和小店密集，适合慢慢走、慢慢看。',
      story: '站点周围的小路很多，棋盘上也一样：找到那条最短的底线通道。',
      nearby: '淮海中路、复兴公园、思南公馆',
      photoGradient: 'linear-gradient(135deg, #d62d42, #7cc7b2 58%, #f7d27a)',
    },
    fen: '2n2k2/p4pp1/Pp5r/6Q1/1q1p4/6Pp/1P3P1P/5BK1 w - - 0 1',
    solution: 'Qd8#',
    motif: '后切入底线',
    rating: 840,
    stars: 3,
    source: '拓展题库 - 娱乐一步杀',
  },
  {
    id: 'wechat-entertainment-4',
    routeId: 'line-1',
    title: '城堡闸门',
    station: {
      name: '衡山路',
      intro: '安静、绿荫和历史建筑很多，和喧闹商圈形成了很有趣的反差。',
      story: '这题不是猛攻，而是像关上一道闸门，让王没有地方可以走。',
      nearby: '衡复风貌区、徐家汇公园、音乐街区',
      photoGradient: 'linear-gradient(135deg, #a51d2d, #6fa66f 45%, #f6d365)',
    },
    fen: 'r1b1k2r/4bppp/p1p2q2/8/8/8/PPPQ1P1P/2KRR3 w - - 0 1',
    solution: 'Qd8#',
    motif: '后穿透底线',
    rating: 860,
    stars: 3,
    source: '拓展题库 - 娱乐一步杀',
  },
  {
    id: 'wechat-entertainment-5',
    routeId: 'line-1',
    title: '长桥转移',
    station: {
      name: '上海火车站',
      intro: '城市铁路与地铁换乘的重要门户，很多旅程从这里开始或结束。',
      story: '棋子也会像列车一样长距离转移，关键是抵达后立刻形成封锁。',
      nearby: '不夜城商圈、苏州河步道、铁路上海站',
      photoGradient: 'linear-gradient(135deg, #e4002b, #8d99ae 55%, #ffd166)',
    },
    fen: 'Q7/8/5pkp/8/5RPK/3rq2P/8/8 w - - 0 1',
    solution: 'Qg8#',
    motif: '后长线转移',
    rating: 880,
    stars: 4,
    source: '拓展题库 - 娱乐一步杀',
  },
  {
    id: 'wechat-entertainment-6',
    routeId: 'line-2',
    title: '王翼采珠',
    station: {
      name: '陆家嘴',
      intro: '高楼天际线最密集的区域之一，也是黄浦江边最醒目的城市名片。',
      story: '这里的杀棋像从高处俯瞰：目标很小，但线路非常清楚。',
      nearby: '东方明珠、上海中心、滨江步道',
      photoGradient: 'linear-gradient(135deg, #76b82a, #63cdda 50%, #f9d65c)',
    },
    fen: '5rk1/5ppp/8/8/3Q4/2B4P/2q2PPK/8 w - - 0 1',
    solution: 'Qxg7#',
    motif: '后吃兵将杀',
    rating: 920,
    stars: 4,
    source: '拓展题库 - 娱乐一步杀',
  },
  {
    id: 'lab-corner-net-1',
    routeId: 'line-2',
    title: '角落封锁',
    station: {
      name: '南京东路',
      intro: '从步行街走到外滩很方便，游客、灯牌和老建筑都很集中。',
      story: '角落杀像走到外滩尽头：边界清楚，逃格自然变少。',
      nearby: '南京路步行街、外滩、和平饭店',
      photoGradient: 'linear-gradient(135deg, #8bc34a, #f5c542 48%, #2d8cc8)',
    },
    fen: '3B4/8/8/8/8/5R2/4Q3/k5K1 w - - 0 1',
    solution: 'Rf1#',
    motif: '车后协同',
    rating: 640,
    stars: 1,
    source: '内置题库 - 基础角落网',
  },
  {
    id: 'lab-diagonal-net-1',
    routeId: 'line-2',
    title: '斜线封锁',
    station: {
      name: '世纪大道',
      intro: '多线换乘站，像棋盘中心一样连接许多方向。',
      story: '这题的象像一条斜穿站厅的通道，看见它，王路就被切断了。',
      nearby: '世纪汇、陆家嘴软件园、浦东商务区',
      photoGradient: 'linear-gradient(135deg, #76b82a, #b6e388 50%, #6c7a89)',
    },
    fen: '4B3/8/8/8/8/7k/5Q2/7K w - - 0 1',
    solution: 'Bd7#',
    motif: '象后封锁',
    rating: 660,
    stars: 1,
    source: '内置题库 - 基础斜线网',
  },
  {
    id: 'lab-file-net-1',
    routeId: 'line-2',
    title: '边线压迫',
    station: {
      name: '上海科技馆',
      intro: '亲子友好度很高，展馆、广场和地下商业空间都很适合探索。',
      story: '科技馆适合问“为什么”：为什么这一步是将杀？因为每个逃格都被控制。',
      nearby: '上海科技馆、世纪公园、花木商圈',
      photoGradient: 'linear-gradient(135deg, #69b72e, #9be7ff 52%, #ffffff)',
    },
    fen: '8/3K4/8/1Q6/8/7k/8/6R1 w - - 0 1',
    solution: 'Qh5#',
    motif: '后车夹击',
    rating: 700,
    stars: 2,
    source: '内置题库 - 边线压迫',
  },
  {
    id: 'lab-knight-cover-1',
    routeId: 'line-2',
    title: '马控逃格',
    station: {
      name: '龙阳路',
      intro: '磁浮、地铁和去浦东机场的路线在这里汇合，很有速度感。',
      story: '马的控制像磁浮一样跳跃，不走直线，却刚好堵住关键逃格。',
      nearby: '磁浮列车、龙阳广场、新国际博览中心',
      photoGradient: 'linear-gradient(135deg, #76b82a, #00a8cc 55%, #f9f871)',
    },
    fen: '8/8/5Q2/8/K7/1N6/k7/8 w - - 0 1',
    solution: 'Qa1#',
    motif: '后马配合',
    rating: 720,
    stars: 2,
    source: '内置题库 - 子力配合',
  },
  {
    id: 'lab-rook-lift-1',
    routeId: 'line-2',
    title: '车横移杀',
    station: {
      name: '虹桥火车站',
      intro: '连接高铁、机场和多条地铁线，是西侧重要交通门户。',
      story: '车的横移像列车进站，看似平移一步，实则把整条线路锁住。',
      nearby: '虹桥枢纽、国家会展中心、虹桥天地',
      photoGradient: 'linear-gradient(135deg, #76b82a, #455a64 55%, #f6c85f)',
    },
    fen: '8/8/5R2/5N1k/5K2/8/8/8 w - - 0 1',
    solution: 'Rh6#',
    motif: '车马封锁',
    rating: 740,
    stars: 2,
    source: '内置题库 - 车马配合',
  },
  {
    id: 'lab-back-rank-1',
    routeId: 'line-10',
    title: '底线切入',
    station: {
      name: '豫园',
      intro: '传统园林、老街和城隍庙区域相邻，转角很多，信息密度很高。',
      story: '底线杀像穿过九曲桥：路线弯弯绕绕，但最后一步非常干脆。',
      nearby: '豫园、城隍庙、老城厢',
      photoGradient: 'linear-gradient(135deg, #c69ad6, #d23b3b 50%, #f4d35e)',
    },
    fen: 'k7/5Q2/2R5/4K3/8/3N4/8/8 w - - 0 1',
    solution: 'Rc8#',
    motif: '车切底线',
    rating: 800,
    stars: 3,
    source: '内置题库 - 底线战术',
  },
  {
    id: 'lab-quiet-queen-1',
    routeId: 'line-10',
    title: '安静后步',
    station: {
      name: '新天地',
      intro: '石库门街区更新后的城市空间，历史和现代商业并置。',
      story: '安静杀棋也有这种气质：表面不吵，结构变化却很大。',
      nearby: '石库门建筑群、太平桥公园、一大会址周边',
      photoGradient: 'linear-gradient(135deg, #b67ad4, #334155 52%, #eab308)',
    },
    fen: '8/8/4b3/1Q6/8/K7/8/4k1N1 w - - 0 1',
    solution: 'Qe2#',
    motif: '静着封杀',
    rating: 830,
    stars: 3,
    source: '内置题库 - 安静杀棋',
  },
  {
    id: 'lab-blocked-king-1',
    routeId: 'line-10',
    title: '堵塞王路',
    station: {
      name: '交通大学',
      intro: '校园、历史建筑和梧桐街区相连，适合做思考型站点。',
      story: '堵塞主题需要先看结构，就像在校园里找到最短但不显眼的小路。',
      nearby: '上海交通大学徐汇校区、武康路、衡复风貌区',
      photoGradient: 'linear-gradient(135deg, #c69ad6, #8b5cf6 50%, #86efac)',
    },
    fen: '4k3/4B3/5K2/7p/8/3R1p2/8/8 w - - 0 1',
    solution: 'Rd8#',
    motif: '车象堵塞',
    rating: 900,
    stars: 4,
    source: '内置题库 - 堵塞主题',
  },
  {
    id: 'lab-knight-anchor-1',
    routeId: 'line-10',
    title: '马锚点',
    station: {
      name: '五角场',
      intro: '东北片区很有辨识度的商圈和交通节点。',
      story: '马像一个锚点，站在不寻常的位置，却让整个局面稳定下来。',
      nearby: '大学路、合生汇、复旦大学周边',
      photoGradient: 'linear-gradient(135deg, #c69ad6, #4f46e5 54%, #f472b6)',
    },
    fen: '2k5/8/2K5/6Q1/1N6/8/8/8 w - - 0 1',
    solution: 'Qg8#',
    motif: '后马锚定',
    rating: 930,
    stars: 4,
    source: '内置题库 - 高阶配合',
  },
  {
    id: 'lab-long-diagonal-1',
    routeId: 'line-10',
    title: '长斜线',
    station: {
      name: '虹桥路',
      intro: '多线交汇，适合把“换乘”理解成棋子协作。',
      story: '后象配合像换乘：两条不同方向的线，最后同时覆盖一个终点。',
      nearby: '宋庆龄陵园、古北片区、虹桥路沿线',
      photoGradient: 'linear-gradient(135deg, #c69ad6, #7dd3fc 48%, #fef3c7)',
    },
    fen: '8/8/8/8/3B4/8/5Q2/2K4k w - - 0 1',
    solution: 'Qg1#',
    motif: '后象长线',
    rating: 840,
    stars: 3,
    source: '内置题库 - 长线控制',
  },
  {
    id: 'lab-black-corner-1',
    routeId: 'line-4',
    title: '黑方角落',
    station: {
      name: '宜山路',
      intro: '环线换乘感很强，是进入综合挑战的合适起点。',
      story: '换到黑方视角，就像在环线上反方向坐车，熟悉的结构要重新看。',
      nearby: '光启城、徐汇商业区、内环沿线',
      photoGradient: 'linear-gradient(135deg, #6f8f3d, #243b24 52%, #d9ed92)',
    },
    fen: '8/7K/8/8/8/6q1/4r3/6k1 b - - 0 1',
    solution: 'Rh2#',
    motif: '黑车封锁',
    rating: 720,
    stars: 2,
    source: '内置题库 - 黑方先行',
  },
  {
    id: 'lab-black-knight-cover-1',
    routeId: 'line-4',
    title: '黑马控格',
    station: {
      name: '海伦路',
      intro: '靠近虹口老城区，街区尺度亲切，适合做观察训练。',
      story: '这题要看到黑马的隐藏控制力，像老街里不明显但关键的转角。',
      nearby: '甜爱路、多伦路文化名人街、虹口足球场周边',
      photoGradient: 'linear-gradient(135deg, #6f8f3d, #8ecae6 48%, #f4a261)',
    },
    fen: '8/8/8/K1k1n3/8/8/8/6q1 b - - 0 1',
    solution: 'Qa1#',
    motif: '黑后马配合',
    rating: 760,
    stars: 2,
    source: '内置题库 - 黑方先行',
  },
  {
    id: 'lab-black-quiet-1',
    routeId: 'line-4',
    title: '黑方静着',
    station: {
      name: '浦东大道',
      intro: '沿江发展带上的一站，城市界面开阔，适合看长线。',
      story: '黑方静着不是退让，而是在更开阔的地方布好最后一张网。',
      nearby: '陆家嘴北滨江、民生码头、浦东大道沿线',
      photoGradient: 'linear-gradient(135deg, #6f8f3d, #2dd4bf 50%, #475569)',
    },
    fen: '8/4r3/8/4q3/1N6/1k6/8/2K5 b - - 0 1',
    solution: 'Qe1#',
    motif: '黑后静着',
    rating: 860,
    stars: 3,
    source: '内置题库 - 黑方先行',
  },
  {
    id: 'lab-black-crossfire-1',
    routeId: 'line-4',
    title: '黑方交叉火力',
    station: {
      name: '蓝村路',
      intro: '浦东老牌换乘站之一，连接生活区和商务区的节奏。',
      story: '最后一站是综合题：后、车、象像三条线交叉，王被困在交汇点。',
      nearby: '塘桥社区、世博滨江、浦东南路沿线',
      photoGradient: 'linear-gradient(135deg, #6f8f3d, #111827 48%, #facc15)',
    },
    fen: '4N3/6r1/3N4/8/2q5/8/2k4K/1b6 b - - 0 1',
    solution: 'Qh4#',
    motif: '后车象交叉',
    rating: 980,
    stars: 5,
    source: '内置题库 - 挑战题',
  },
];

export const puzzles = [
  ...pdfPuzzles,
  ...builtInPuzzles.map(enrichPuzzle),
];
